Person and fileReader tasks done
YuliyaLahun/Yuliya_Lahun_AT_G6 pull request #16
Opened 2022-11-02 18:13 UTC by YuliyaLahun

2022-11-03 17:21 UTC, nastatest requested changes

2022-11-03 17:21 UTC, nastatest commented on src/main/java/homework/day10/PersonStream.java
> +        }
мне здаецца, тут таксама трэба генерыць праз стрым

2022-11-03 19:10 UTC, YuliyaLahun commented on src/main/java/homework/day10/PersonStream.java
> +        }
изменила на генерацию через стрим)

2022-11-03 20:45 UTC, nastatest approved these changes

2022-11-03 21:40 UTC, nastatest commented on src/main/java/homework/day10/PersonStream.java
> +        return random.nextInt(max - min) + min;
вось тут яшчэ трэба +1 зрабіць у дужках, бо так у цябе ніколі не выпадае 31, бо рандом запускаецца на 16 інтоў, а ад 15 да 31 - гэта 17 інтоў :)

2022-11-04 18:21 UTC, nastatest approved these changes

2022-11-04 20:06 UTC, merged