homeWork day 12 threads task 1.2 and 1.3 done
YuliyaLahun/Yuliya_Lahun_AT_G6 pull request #21
Opened 2022-11-11 05:34 UTC by YuliyaLahun

2022-11-11 18:17 UTC, nastatest approved these changes

2022-11-11 18:27 UTC, nastatest requested changes

2022-11-11 18:27 UTC, nastatest commented on src/main/java/homework/day12/Task1_4.java
> +
калі запускаю код у сябе, у мяне пікае толькі адна мыш некалькі разоў(

2022-11-11 18:27 UTC, nastatest commented on src/main/java/homework/day12/Task1_4.java
> +    private static int numberOfMouses = 3;
а што гэта за лічба?) і яшчэ я не знайшла, дзе 280 мышэй)

2022-11-17 20:36 UTC, nastatest requested changes

2022-11-17 20:36 UTC, nastatest commented on src/main/java/homework/day12/Task1_6.java
> +            peepAndRemoveUnEvenMouse(mouses, evenMouses);
толькі туту peepAndRemoveEvenMouse) мышы цотныя)

2022-11-17 20:36 UTC, nastatest commented on src/main/java/homework/day12/Task1_7.java
> +        t5.start();
не магу дагнаць пакуль, у чым справа, але калі запускаю гэты код, вынік заўсёды адзін: спачатку запускаецца 1-ы паток, пікае роўна 20 мышэй, пасля запускаецца 5-ы, зноў пікае роўна 20 мышэй, а пасля ўсё падае( IndexOutOfBoundsException

2022-11-17 22:07 UTC, YuliyaLahun commented on src/main/java/homework/day12/Task1_4.java
> +
исправлено

2022-11-17 22:07 UTC, YuliyaLahun commented on src/main/java/homework/day12/Task1_4.java
> +    private static int numberOfMouses = 3;
исправлено

2022-11-17 22:46 UTC, YuliyaLahun commented on src/main/java/homework/day12/Task1_7.java
> +        t5.start();
тут была ошибка с количеством мышей, теперь может будет хватать времени для переключения потоков) а индекс аут оф баунд - не думаю что мы с этим можем что-то сделать. на самом деле если дождаться конца исполнения, то они во всех тасках будут(

2022-11-21 20:04 UTC, nastatest approved these changes

2022-11-24 10:08 UTC, merged